# Generated by Django 3.2 on 2021-04-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_topping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={},
        ),
    ]
